'''RemehaCAN constants'''

STATUSDICT = {
	0: 'Stand-by',
	1: 'Warmtevraag',
	2: 'Start generator',
	3: 'Generator CV',
	4: 'Generator SWW',
	5: 'Stop generator',
	6: 'Nadraaitijd pomp',
	7: 'Koelen actief',
	8: 'Gecontroleerde stop',
	9: 'Blokkering',
	10: 'Vergrendeling',
	11: 'Belastingstest min.',
	12: 'Belastingst. CH max',
	13: 'Belastingst. SWW max',
	15: 'Handm. warmtevraag',
	16: 'Vorstbeveiliging',
	17: 'Ontluchting',
	18: 'Regeleenheid koelen',
	19: 'Reset w uitgevoerd',
	20: 'Autovullen w uitgevoerd',
	21: 'Gepauzeerd',
	22: 'Geforc. kalibratie',
	23: 'Fabriekstest',
	24: 'Hydraul. inregelen',
	200: 'Apparaatmodus',
	254: 'Onbekend'
}

SUBSTATUSDICT = {
	0: 'Stand-by',
	1: 'AntiCyclus',
	2: 'SluitHydraulKlep',
	3: 'SluitPomp',
	4: 'WachtOpStartCond.',
	10: 'SluitExtGasKlep',
	11: 'StartRookGasKlep',
	12: 'SluitRookGasKlep',
	13: 'VentiVoorOntluchten',
	14: 'WachtOpVrijgaveSign',
	15: 'BranderOpComm.NaarSu',
	16: 'VpsTest',
	17: 'Voorontsteking',
	18: 'Ontsteking',
	19: 'VlamControle',
	20: 'TussentijdsOntlucht',
	21: 'Generator start',
	30: 'Normaal Int.instelpt',
	31: 'Beperkt Int.instelpt',
	32: 'NormaleVerm.Controle',
	33: 'GradLevel1PowerCtrl',
	34: 'GradLevel2PowerCtrl',
	35: 'GradLevel3PowerCtrl',
	36: 'BeschVlamVerm.regel.',
	37: 'StabilisatieTijd',
	38: 'KoudeStart',
	39: 'ChHervatten',
	40: 'SuVerwijderBrander',
	41: 'Vent.NaarNaOntlucht.',
	42: 'OpenExtRookGasKlep',
	43: 'StopVent.NaarRGKTpm',
	44: 'StopVentilator',
	45: 'Bep.VermOpTRookGas',
	46: 'AutoVulInstallatie.',
	47: 'AutoVullenBijvullen',
	48: 'Verlaagd instelpunt',
	49: 'Offset aanpassing',
	60: 'PompNadraaitijd',
	61: 'OpenPomp',
	62: 'OpenHydraulischeKlep',
	63: 'RegelAntiCyclusTimer',
	65: 'Generator vrijgegvn',
	66: 'WPStrmBovTMaxResAAN',
	67: 'ExtOmstStopWarmtePmp',
	68: 'HybridStopWarmptePmp',
	69: 'OntdooiMetWP',
	70: 'OntdooiMetRes',
	71: 'OntdooiMetWPenRes',
	72: 'PompBronBijverwRun',
	73: 'WPStroomBovTMax',
	74: 'BronPompNaDraai',
	75: 'VochtSensorStopWP',
	76: 'WaterStroomStopWP',
	78: 'VochtighInt.Instelpt',
	79: 'Generators vrijgegvn',
	80: 'WPOntlastVoorKoelen',
	81: 'BuitenTempStopWP',
	82: 'WarmtePUitBovLimiet',
	83: 'OntluchPompAanKlepCV',
	84: 'OntlPompAanKlepSWW',
	85: 'OntluchPompUitKlepCV',
	86: 'OntlPompUitKlepSWW',
	88: 'BLInvoerResBeperkt',
	89: 'WPBeperkt',
	90: 'BijverwEnWPBeperkt',
	91: 'BLInvoerLaagTarief',
	92: 'FV-MetWP',
	93: 'PV-MetWPEnBijverw',
	94: 'BLInvoerSmartGrid',
	95: 'WachtOpWaterdruk',
	96: 'GeenProducentBeschik',
	97: 'Hoger min vermogen',
	98: 'Lager max vermogen',
	102: 'VrijKoelenPompUit',
	103: 'VrijKoelenPompAAN',
	104: 'BronPompVoorLoop',
	105: 'Kalibratie',
	106: 'Blokkering actief',
	107: 'Opwarmen',
	108: 'IJsvorming ontdooien',
	109: 'Preventief ontdooien',
	200: 'Initialiseren gereed',
	201: 'CSU initialiseren',
	202: 'Init. identificaties',
	203: 'Init. BL-parameter',
	204: 'Init. veiligh.eenh.',
	205: 'Init. blokkeren',
	254: 'StatusOnbekend',
	255: 'SuOutOfResetsWait1Hr'
}
