"""RemehaCAN constants"""

STATUSDICT = {
        0: 'Stand-by',
        1: 'Warmtevraag',
        2: 'Start generator',
        3: 'Generator CV',
        4: 'Generator SWW',
        5: 'Stop generator',
        6: 'Nadraaitijd pomp',
        7: 'Koelen actief',
        8: 'Gecontroleerde stop',
        9: 'Blokkering',
        10: 'Vergrendeling',
        11: 'Belastingstest min.',
        12: 'Belastingst. CH max',
        13: 'Belastingst. SWW max',
        15: 'Handm. warmtevraag',
        16: 'Vorstbeveiliging',
        17: 'Ontluchting',
        18: 'Regeleenheid koelen',
        19: 'Reset w uitgevoerd',
        20: 'Autovullen w uitgevoerd',
        21: 'Gepauzeerd',
        22: 'Geforc. kalibratie',
        23: 'Fabriekstest',
		71: 'Onbekend',
        200: 'Apparaatmodus',
        254: 'Onbekend'
}

SUBSTATUSDICT = {
        0: 'Stand-by',
        1: 'AntiCyclus',
        2: 'SluitHydraulKlep',
        3: 'SluitPomp',
        4: 'WachtOpStartCond.',
        10: 'SluitExtGasKlep',
        11: 'StartRookGasKlep',
        12: 'SluitRookgasKlep',
        13: 'VentiVoorOntluchten',
        14: 'WachtOpVrijgaveSign',
        15: 'BranderOpComm.NaarSu',
        16: 'VpsTest',
        17: 'Voorontsteking',
        18: 'Ontsteking',
        19: 'VlamControle',
        20: 'TussentijdsOntlucht',
        30: 'Normaal Int.instelp',
        31: 'Beperkt Int.instelp',
        32: 'NormaleVerm.Controle',
        33: 'GradLevel1PowerCtrl',
        34: 'GradLevel2PowerCtrl',
        35: 'GradLevel3PowerCtrl',
        36: 'BeschVlamVerm.regel',
        37: 'StabilisatieTijd',
        38: 'KoudeStart',
        39: 'ChHervatten',
        40: 'SuVerwijderBrander',
        41: 'Vent.NaarNaOntlucht.',
        42: 'OpenExtRookGasKlep',
        43: 'StopVent.NaarRGKTpm',
        44: 'StopVentilator',
        45: 'Bep.VermOpTRookGas',
        46: 'AutoVulInstallatie',
        47: 'AutoVullenBijvullen',
        48: 'Verlaagd instelpunt',
        49: 'Offset aanpassing',
        60: 'PompNadraaitijd',
        61: 'OpenPomp',
        62: 'OpenHydraulischeKlep',
        69: 'OntdooimetWP',
		70: 'OntdooimetRes',
		71: 'OntdooimetWPenRes',
        94: 'Slim stroomnet (SG)',
		108: 'IJsvorming ontdooien',
		109: 'Preventief ontdooien',
        200: 'Apparaatmodus',
        254: 'Onbekend'
}
